### ISSUE TITLE
Habits shown belong to the latest user to log-in

### ISSUE THREAD

**Issue by dev0T** [daya0576/beaverhabits#112]
Currently, we are experiencing a session issue when more than one user is using the server, the habits shown in the app belong to the latest user to log-in.

For example:

I log in, I am able to see my habits like normal. If my spouse logs in right after me, when I access the app again, I can only see his habits. We only realized a few weeks ago when we tried to use the app at the same time.

**Steps to reproduce:**

- Log-in on the app with user 1 on a client
- Able/change to see user 1 habits
- Log-in on the app with user 2 on another client
- User 1 is able to see/change user 2 habits after accessing the app unless it starts a new session

Our docker-compose:
```
services:
  beaverhabits:
    image: daya0576/beaverhabits:latest
    container_name: beaverhabits
    restart: unless-stopped
    user: 1000:1000 # User permissions of your docker or default user.
    environment:
      - FIRST_DAY_OF_WEEK=6 # By default, the first day of the week is set as Monday. To change it to Sunday, you can set it as 6.
      - HABITS_STORAGE=USER_DISK # DATABASE stores in a single SQLite database named habits.db. USER_DISK option saves in a local json file.
      - MAX_USER_COUNT=2 # By setting it to 1, you can prevent others from signing up in the future.
    volumes:
      - [desired directory]:/app/.user/ # Change directory to match your docker file scheme.
    ports:
      - 15808:8080
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
```

Please let me know if I can provide anything else.

Appreciate this repo and your time, thanks! <3
