### ISSUE TITLE
Unable to open database

### ISSUE THREAD

**Issue by Elekam** [daya0576/beaverhabits#23]
I used composerize to make a docker compose of this container, but when I run the container I encounter this error:
[_beaverhabits_logs.txt](https://github.com/user-attachments/files/18031609/_beaverhabits_logs.txt)

Docker compose:
```
version: "3"
services:
    beaverhabits:
        image: daya0576/beaverhabits:latest
        container_name: beaverhabits
        environment:
            - FIRST_DAY_OF_WEEK=0
            - HABITS_STORAGE=USER_DISK
            - MAX_USER_COUNT=5
            - INDEX_SHOW_HABIT_COUNT=false
        volumes:
            - /docker/beaverhabits:/app/.user/
        ports:
            - 8036:8080
        restart: unless-stopped
```

        
I checked the permissions of the volume and the container should have permissions to write. Honestly dont know why it cant create the database, or why its even attempting to create one when USER_DISK should make it use a json?
I played around with the env vars but they also didnt seem to change anything.

Maybe this is a very obvious error that Im just too overtired/blind to see right now?

**Comment by daya0576** [comment]
@Elekam, thanks for reaching out. Please refer to #22 to address this permission issue.

**Comment by daya0576** [comment]
Tested in my ubuntu machine, specifying user would solve this issue. 

For docker compose, it should be something like this: 
```
services:
  myservice:
    image: myimage
    user: "$(id -u):$(id -g)"
```

**Comment by dmarcoux** [comment]
I am also having permission issues. In my case, this is what I get:

```
INFO:     Starting BeaverHabits...
INFO:     Started server process [4]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
ERROR:nicegui:[Errno 13] Permission denied: '/app/.nicegui'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/nicegui/events.py", line 432, in handle_event
    result = cast(Callable[[], Any], handler)()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nicegui/storage.py", line 68, in backup
    self.filepath.parent.mkdir(exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/app/.nicegui'
```

I am running the container with Podman, as a rootless user. I set the user and group to the Podman user. As for the host path which is mounted as a volume, its owner is also the same Podman user.

**Comment by daya0576** [comment]
The key here is to ensure that the owner of the mounted folder is the same as the container user.

Here is a general approach to fix this permission issue:
```bash
# Step1: Find current container user
$ docker run --rm daya0576/beaverhabits:0.3.4 cat /etc/passwd | id -u
1000

# Step2: Change folder permissions and ownership
$ sudo chown -R 1000 .user
```

**Comment by daya0576** [comment]
Alternatively, you can adjust the container user to match the owner of the folder:

```
services:
  myservice:
    image: myimage
    user: "$(id -u):$(id -g)"
```

**Comment by Elekam** [comment]
Hello, thanks a lot. Sadly this command:
> The key is to ensure that the owner of the mounted folder is the same as the container user.
> 
> Here is a general approach to fix this permission issue:
> 
> ```shell
> # Step1: Find current container user
> $ docker run --rm daya0576/beaverhabits:0.3.4 cat /etc/passwd | id -u
> 1000
> 
> # Step2: Change folder permissions and ownership
> $ sudo chown -R 1000 .user
> ```

didnt work for me, it gave out
```
0
write /dev/stdout: broken pipe
```

But setting `user: '1000:1000' `, which is my default user and the current owner of the volume, worked.
Again, thanks :)

**Comment by samuelrey** [comment]
running into this issue as well, but adding user didn't help.
```
services:
    beaverhabits:
        image: daya0576/beaverhabits:latest
        container_name: beaverhabits
        user: 1000:1000
        environment:
            - HABITS_STORAGE=USER_DISK
        volumes:
          - /docker/beaverhabits:/app/.user
        ports:
          - 9000:8080
        restart: unless-stopped
```
