### ISSUE TITLE
API habit completion returns error

### ISSUE THREAD

**Issue by frankrehfeld** [daya0576/beaverhabits#55]
When trying to complete a habit via API it returns an error.

```
curl --request POST --url http://192.168.1.60:8081/api/v1/habits/fc901c/completions \
 --header 'accept: application/json' \
 --header 'authorization: Bearer xxx' \
 --data '{"done": true, "date_fmt": "%d-%m-%Y", "date": "01-01-2025"}
```
returns the following error message:
```
{"detail":[{"type":"model_attributes_type","loc":["body"],"msg":"Input should be a valid dictionary or object to extract fields from","input":"{\"done\": true, \"date_fmt\": \"%d-%m-%Y\", \"date\": \"01-01-2025\"}"}]}
```

**Comment by frankrehfeld** [comment]
Hi. The `'` was lost when copying the request into the issue. The request was done with the trailing `'` and returned the error. I've just controlled it and got the same behaviour.

**Comment by daya0576** [comment]
OK, could you add the `content-type` header to your request, here is an [example](https://github.com/daya0576/beaverhabits/wiki/Beaver-Habit-Tracker-API-How%E2%80%90to-Guide#task3---complete-habit).

**Comment by frankrehfeld** [comment]
Thanks for your help. It worked as expected.

FYI: I used it to build a switch for home assistant to mark a habit as done. This can be achieved by implementing a rest switch using the following code:
```
- platform: rest
  resource: http://192.168.1.60:8081/api/v1/habits/fc901c/completions
  params:
    date_start: '{{ now().strftime("%d-%m-%Y") }}'
    date_end: '{{ now().strftime("%d-%m-%Y") }}'
    sort: asc
  headers:
    content-type: application/json
    accept: application/json
    authorization: Bearer xxx
  is_on_template: '{{ now().strftime("%d-%m-%Y") in value_json }}'
  body_on: '{"done": true, "date": "{{ now().strftime("%d-%m-%Y") }}" }'
  body_off: '{"done": false, "date": "{{ now().strftime("%d-%m-%Y") }}" }'
  name: medicine
  icon: mdi:pill
```

Maybe you are interested in adding it in the documentation.
