### ISSUE TITLE
Add Compose Template in README.md

### ISSUE THREAD

**Issue by TechHutTV** [daya0576/beaverhabits#57]
Can you add something like this so people can easily add it with compose or to an existing stack:

Example with Docker Compose: 
``` yaml
services:
    beaverhabits:
        container_name: beaverhabits
        user: 1000:1000 # User permissions of your docker or default user.
        environment:
            - FIRST_DAY_OF_WEEK=0 # By default, the first day of the week is set as Monday. To change it to Sunday, you can set it as 6.
            - HABITS_STORAGE=USER_DISK # DATABASE stores in a single SQLite database named habits.db. USER_DISK option saves in a local json file.
            - MAX_USER_COUNT=1 # By setting it to 1, you can prevent others from signing up in the future.
            - ENABLE_IOS_STANDALONE=false # Experiential feature to enable standalone mode on iOS. The default setting is false.
            - INDEX_SHOW_HABIT_COUNT=false # To display the total completed count badge on the main page. The default setting is false.
        volumes:
            - /path/to/beaver/habits:/app/.user/ # Change directory to match your docker file scheme.
        ports:
            - 8080:8080
        restart: unless-stopped
        image: daya0576/beaverhabits:latest
```
