### ISSUE TITLE
Support SSO authentication

### ISSUE THREAD

**Issue by bogdanr** [daya0576/beaverhabits#61]
It would be nice if it would support SSO authentication similar to how openwebui does it.
https://docs.openwebui.com/features/sso
I configure this `WEBUI_AUTH_TRUSTED_EMAIL_HEADER=Cf-Access-Authenticated-User-Email` environment variable and I can let Cloudflare handle the authentication for me.

**Comment by daya0576** [comment]
Hi @bogdanr, just had a chance to look at the wiki page. 

It looks pretty cool! --- I'm using Cloudflare Tunnel too :)

Definitely will integrate it when I'm available.

**Comment by daya0576** [comment]
Hi @bogdanr , this feature is available now with the latest release `0.4.3` 

Please try the environment variable below to enable cloudfront trust header: 

```
TRUSTED_EMAIL_HEADER=Cf-Access-Authenticated-User-Email
```

**Comment by daya0576** [comment]
Closing it after testing in my own cloudflare tunnel, feel free to reopen it if you have any other questions.

**Comment by benjick** [comment]
Works with Authelia 👍 

`TRUSTED_EMAIL_HEADER=Remote-Email`

But it's not published to `:latest` on Docker hub, I had to use the `:0.4.3-hotfix3`-tag

**Comment by Eragos** [comment]
> Works with Authelia 👍
> 
> `TRUSTED_EMAIL_HEADER=Remote-Email`
> 
> But it's not published to `:latest` on Docker hub, I had to use the `:0.4.3-hotfix3`-tag

Hey there! Do you think there’s any way we can get our hands on the Authelia configuration?

**Comment by benjick** [comment]
@Eragos it's nothing special:

```yml
access_control:
  default_policy: deny
  rules:
    - domain: "habits.example.com"
      policy: one_factor
```

**Comment by Eragos** [comment]
Thanks for your quick reply! That sounds pretty standard. But I was wondering about the ENV args on beaverhabits container. I believe the Authelia trust header is usually found in `HTTP_X_FORWARDED_USER`.

**Comment by benjick** [comment]
You can find all headers here: https://www.authelia.com/integration/trusted-header-sso/introduction/#response-headers

I also forward the headers in traefik like this:
```yml
http:
  middlewares:
    auth:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://auth.example.com
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
```
