### ISSUE TITLE
[Feature Request] Docker Healthchecks

### ISSUE THREAD

**Issue by alx-xlx** [daya0576/beaverhabits#73]
Hey it would be an awesome feature to add the docker healthchecks.

I couldn't use `curl` , `wget` etc

**Comment by daya0576** [comment]
Hi thanks for opening the request, could you share any wiki or documentation about "docker healthchecks"?

**Comment by sebbo2002** [comment]
Docker Reference: https://docs.docker.com/reference/dockerfile/#healthcheck
Usually it's a HTTP Request to some health endpoint.

**Comment by alx-xlx** [comment]
Yes that's correct, it is probably an easy fix. Just including either `curl`, `wget`, `netstat` commands etc in the docker image would do the trick.

and the following compose file with healthchecks will work fine.

```
services:
  beaverhabits:
    container_name: beaverhabits
    user: 1000:1000 # User permissions of your docker or default user.
    environment:
      # See the note below to find all the environment variables
      - HABITS_STORAGE=USER_DISK # DATABASE stores in a single SQLite database named habits.db. USER_DISK option saves in a local json file.
    volumes:
      - /home/pi/data/beaverhabits/habits:/app/.user/ # Change directory to match your docker file scheme.
    ports:
      - 8080:8080
    restart: unless-stopped
    image: daya0576/beaverhabits:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
```
